### ISSUE TITLE
Foodento Website.

### ISSUE THREAD

**Issue by ravi4488** [AryanBarsaiyan/DSA_Webd_Project_BlockChain_hacktoberfest2022#149]
This is a responsive food serving website (frontend) using HTML, CSS & JS.
@AryanBarsaiyan kindly assign me this under Hacktoberfest 2022.

**Comment by AryanBarsaiyan** [comment]
okk

**Comment by ravi4488** [comment]
@AryanBarsaiyan kindly review my PR #154 .
