### ISSUE TITLE
The Shekhar's - Food Serving Website

### ISSUE THREAD

**Issue by afterallvishal** [AryanBarsaiyan/DSA_Webd_Project_BlockChain_hacktoberfest2022#157]
@AryanBarsaiyan kindly assign me this under Hacktoberfest 2022.
This is a online Food Serving Website named The Shekhar's using HTML & CSS.

**Comment by AryanBarsaiyan** [comment]
okk

**Comment by afterallvishal** [comment]
@AryanBarsaiyan kindly review my PR #158 .
