### ISSUE TITLE
Like to add Famous and important Knapsack problem in Dp section

### ISSUE THREAD

**Issue by Kavya2719** [AryanBarsaiyan/DSA_Webd_Project_BlockChain_hacktoberfest2022#182]
Hello @AryanBarsaiyan, I was reviewing your dp section and I found 0-1 Knapsack missing and you will also be knowing that how important and helpful that algorithm is. So I would like to add self explanatory code for that, may you assign me this.
And My query is I can directly send the cpp file or I have to make a different html file. Thanks

**Comment by AryanBarsaiyan** [comment]
send java file or make a different HTML file
