### ISSUE TITLE
Will add detecting cycle in directed graph using three colors

### ISSUE THREAD

**Issue by kartik-ey1** [AryanBarsaiyan/DSA_Webd_Project_BlockChain_hacktoberfest2022#28]
An interesting problem :)

**Comment by AryanBarsaiyan** [comment]
Not accepting CPP/C DSA codes
Alternative ->
1)Create a page using HTML & CSS Add DSA problem statement and solution in that
2)You can contribute in python and java OR
Ask for an issue assigned.
3)Add any web Project.
